nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
nombre <- "Juan"
cat("Hola,", nombre, "!\n")
